server:
  port: 5763

spring:
  datasource:
    url: jdbc:mysql://sejonggoodsmall.ctgs2a9du4h5.ap-northeast-2.rds.amazonaws.com:3306/sejonggoodsmall
    username: admin
    password: 9132wjddus
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
