cloud:
  aws:
    credentials:
      access-key: AKIAYBWDP44IA3OP7URV
      secret-key: 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
    s3:
      bucket: sejonggoodsmall
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB