server:
  port: 5763

spring:
  datasource:
    url: jdbc:mysql://sejonggoodsmall2.ctgs2a9du4h5.ap-northeast-2.rds.amazonaws.com:3306/sejonggoodsmall
    username: admin
    password: 9132wjddus
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: sejonggoodsmall2@gmail.com
    password: wqzzioqnltxuvouy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    com.amazonaws.util.EC2MetadataUtils: error